import { Header, Footer } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NextTopLoader from "nextjs-toploader";
export const metadata: Metadata = {
  title: "Whismy Words",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <NextTopLoader color="#ffffff" />
        <ToastContainer theme="colored" position="top-center" />
        <Header />
        {children}
        <Footer />
      </Providers>
    </html>
  );
}
